name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      working-directory: ./helloworld
      run: mvn clean install
  
    - name: Build Docker image
      working-directory: ./helloworld
      run: docker build -t my-spring-app .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: debuging 
      run: docker images 
    - name: list files
      run: ls -l helloworld
    - name: tag the image
      run: docker tag my-spring-app mah1191/helloworld:v0.0001
      
    - name: Push Docker image
      run: docker push mah1191/helloworld:v0.0001

    - name: Deploy to Docker container
      run: |
        docker run -d -p 8080:8080 --name my-spring-app my-spring-app
